-- MySQL Script generated by MySQL Workbench
-- 10/29/16 21:19:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clasificacion_rutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clasificacion_rutina` (
  `idclasificacion_rutina` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idclasificacion_rutina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rutinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rutinas` (
  `idrutinas` INT NOT NULL,
  `url_imagen` VARCHAR(45) NOT NULL,
  `duracion` INT(11) NOT NULL,
  `clasificacion_rutina_idclasificacion_rutina` INT NOT NULL,
  PRIMARY KEY (`idrutinas`, `clasificacion_rutina_idclasificacion_rutina`),
  INDEX `fk_rutinas_clasificacion_rutina1_idx` (`clasificacion_rutina_idclasificacion_rutina` ASC),
  CONSTRAINT `fk_rutinas_clasificacion_rutina1`
    FOREIGN KEY (`clasificacion_rutina_idclasificacion_rutina`)
    REFERENCES `mydb`.`clasificacion_rutina` (`idclasificacion_rutina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horarios` (
  `idhorarios` INT NOT NULL,
  `dia_inicio` VARCHAR(45) NOT NULL,
  `dia_fin` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idhorarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tarea` (
  `idtarea` INT NOT NULL,
  `horarios_idhorarios` INT NOT NULL,
  `rutinas_idrutinas` INT NOT NULL,
  PRIMARY KEY (`idtarea`, `horarios_idhorarios`, `rutinas_idrutinas`),
  INDEX `fk_tarea_horarios1_idx` (`horarios_idhorarios` ASC),
  INDEX `fk_tarea_rutinas1_idx` (`rutinas_idrutinas` ASC),
  CONSTRAINT `fk_tarea_horarios1`
    FOREIGN KEY (`horarios_idhorarios`)
    REFERENCES `mydb`.`horarios` (`idhorarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_rutinas1`
    FOREIGN KEY (`rutinas_idrutinas`)
    REFERENCES `mydb`.`rutinas` (`idrutinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area_laboral` (
  `idarea_laboral` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idarea_laboral`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trabajadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trabajadores` (
  `idtrabajadores` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `area_laboral_idarea_laboral` INT NOT NULL,
  PRIMARY KEY (`idtrabajadores`, `area_laboral_idarea_laboral`),
  INDEX `fk_trabajadores_area_laboral1_idx` (`area_laboral_idarea_laboral` ASC),
  CONSTRAINT `fk_trabajadores_area_laboral1`
    FOREIGN KEY (`area_laboral_idarea_laboral`)
    REFERENCES `mydb`.`area_laboral` (`idarea_laboral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trabajadores_has_tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trabajadores_has_tarea` (
  `trabajadores_idtrabajadores` INT NOT NULL,
  `tarea_idtarea` INT NOT NULL,
  PRIMARY KEY (`trabajadores_idtrabajadores`, `tarea_idtarea`),
  INDEX `fk_trabajadores_has_tarea_tarea1_idx` (`tarea_idtarea` ASC),
  INDEX `fk_trabajadores_has_tarea_trabajadores1_idx` (`trabajadores_idtrabajadores` ASC),
  CONSTRAINT `fk_trabajadores_has_tarea_trabajadores1`
    FOREIGN KEY (`trabajadores_idtrabajadores`)
    REFERENCES `mydb`.`trabajadores` (`idtrabajadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trabajadores_has_tarea_tarea1`
    FOREIGN KEY (`tarea_idtarea`)
    REFERENCES `mydb`.`tarea` (`idtarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
